-- AlterTable
ALTER TABLE "MarketDaily" ADD COLUMN     "adjClose" DOUBLE PRECISION,
ADD COLUMN     "high" DOUBLE PRECISION,
ADD COLUMN     "low" DOUBLE PRECISION,
ADD COLUMN     "open" DOUBLE PRECISION;

